<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="MIBLR-LP0015" name="com.adjudication.test.viewclaims.ffsprofessional.pend.ViewClaimsFromFFSProApproved" tests="4" failures="1" timestamp="2021-03-26T17:43:51 IST" time="246.352" errors="1">
  <testcase name="SaveValiForApporvedStatusFromFFSProPendNegTC" time="48.739" classname="com.adjudication.test.viewclaims.ffsprofessional.pend.ViewClaimsFromFFSProApproved">
    <failure type="java.lang.AssertionError" message="Value is not present in drop down">
      <![CDATA[java.lang.AssertionError: Value is not present in drop down
at org.testng.Assert.fail(Assert.java:99)
at com.adjudication.test.viewclaims.ffsprofessional.pend.ViewClaimsFromFFSProApproved.SaveValiForApporvedStatusFromFFSProPendNegTC(ViewClaimsFromFFSProApproved.java:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- SaveValiForApporvedStatusFromFFSProPendNegTC -->
  <system-out/>
  <testcase name="SaveValiForDenyStatusFromFFSProPendNegTC" time="54.177" classname="com.adjudication.test.viewclaims.ffsprofessional.pend.ViewClaimsFromFFSProApproved">
    <error type="java.lang.Exception" message="Value is not present in drop down">
      <![CDATA[java.lang.Exception: Value is not present in drop down
at com.adjudication.seleniumactions.implementation.DropDownControls.selectViaVisibleTextFromList(DropDownControls.java:56)
at com.adjudication.pages.viewclaims.serviceDetails.ServiceDetailsExpansionPage.selectStatus(ServiceDetailsExpansionPage.java:274)
at com.adjudication.test.viewclaims.ffsprofessional.pend.ViewClaimsFromFFSProApproved.SaveValiForDenyStatusFromFFSProPendNegTC(ViewClaimsFromFFSProApproved.java:135)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- SaveValiForDenyStatusFromFFSProPendNegTC -->
  <system-out/>
  <testcase name="moveToDenyFromFFSProPendNegTC" time="71.415" classname="com.adjudication.test.viewclaims.ffsprofessional.pend.ViewClaimsFromFFSProApproved"/>
  <system-out/>
  <testcase name="moveToApporveFromFFSProPendPositiveTC" time="72.021" classname="com.adjudication.test.viewclaims.ffsprofessional.pend.ViewClaimsFromFFSProApproved"/>
  <system-out/>
</testsuite> <!-- com.adjudication.test.viewclaims.ffsprofessional.pend.ViewClaimsFromFFSProApproved -->
